version: "3"
services:
  massa-core:
    build:
      context: .
      args:
        - VERSION=MAIN.2.1
    container_name: massa-core
    restart: always
    environment:
      - WALLETPWD=${WALLETPWD}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
    ports:
      - "31244:31244"
      - "31245:31245"
      - "33035:33035"
      - "31248:31248"
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    volumes:
      - ./massa_mount:/massa_mount

volumes:
  massa-core:
